### ISSUE TITLE
Allow literal shorthand in S.union

### ISSUE THREAD

**Issue by justin0mcateer** [DZakh/rescript-schema#94] opened 2024-09-29 21:48 UTC
The new literal shorthand is nice, thanks for that.

I was wondering if it would possible to enable using this with the S.union function?

I have many union types in TypeScript which are effectively string enumerations.

For example:
type FooBar = 'foo' | 'bar' | 'fizz' | 'buzz';

It would be nice to be able to define schema as:
const FooBarSchema = S.union(['foo', 'bar', 'fizz', 'buzz']);

Or, at least:
const FooBarSchema = S.union(['foo' as const, 'bar as const', 'fizz' as const, 'buzz' as const]);

Currently, either such usage seems to cause both type and runtime errors.

**Comment by DZakh** [comment] 2024-09-30 08:25
This should be doable. I recently added https://github.com/DZakh/rescript-schema/blob/main/docs/rescript-usage.md#enums to ReScript API, and I can add it to TS API as well.

The only challenge here is to create a TS type for it. Contributions are welcome

**Comment by DZakh** [comment] 2024-09-30 08:26
Here's the type for `S.union` for reference https://github.com/DZakh/rescript-schema/blob/d7805393281f87222a0e1fa2692be2cb32ecc351/src/S.d.ts#L132-L137

**Comment by DZakh** [comment] 2024-10-11 06:45
I implemented it in the commit https://github.com/DZakh/rescript-schema/commit/b32779dec34c6d9b5edd7db0cbefb6e5ca305f5e

<img width="320" alt="image" src="https://github.com/user-attachments/assets/f214a0cc-4aeb-4391-bcee-1a45425d9939">

The result is even more powerful than you asked since it allows objects and tuples.

I'll do a v8.4 release after fixing one regression and writing the documentation. I can't promise for it to happen soon, because I'm currently on vacation in South Korea.

**Comment by DZakh** [comment] 2024-10-17 07:22
Released as a part of https://github.com/DZakh/rescript-schema/releases/tag/v8.4.0

**Closed by DZakh** 2024-10-17 07:22 UTC
Labels: enhancement, good first issue, v9
